### ISSUE TITLE
Focus On FullScreen Button Doesn'T DisAppear When Clicking And Releasing

### ISSUE THREAD

**Issue by ghost** [w0bm/w0bm.com#252] opened 2018-02-13 21:27 UTC
Hello I Like CapitaLize So When You Click Fulscreen, Then Not Click Fulscreen, Then Focus Still There, So When Space To Pause, Video UnFulScreens. Pls Fix.
https://koyaanis.com/i/1518557139181.webm

**Comment by ghost** [comment] 2018-02-13 21:27
https://koyaanis.com/i/1518557139181.webm

**Comment by ghost** [comment] 2018-02-13 21:27
sry lool first time github ^^

**Comment by belst** [comment] 2018-02-13 21:47
Duplicate of #247

**Closed as completed by belst** 2018-02-13 21:47 UTC
